services:
  - type: web
    name: evolucao-api
    runtime: node
    plan: free
    rootDir: dashboard
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_QA_LOCAL_BYPASS
        value: "0"
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: 123456
      - key: JWT_SECRET
        value: super_secret
      - key: DEFAULT_CLIENT_ID
        value: admin
      - key: CLIENT_API_KEYS
        value: '{"admin":"123456"}'
      - key: APP_API_KEY
        value: 123456
